### ISSUE TITLE
MainActivity

### ISSUE THREAD

**Issue by jamilelima** [blueevee/IMCCalculator#1]
Você não estava conseguindo passar para a outra tela por causa do cast (conversão) que você estava fazendo nos dados. Indico que você passe os dados como string e trate na tela de resultados mesmo. Assim:
```
fun clickCalcBTN(view: View) {
        val intent = Intent(this, ResultCalcIMC::class.java).apply {
            putExtra("HEIGHT",heightEDTXT?.text.toString())
            putExtra("WEIGHT", weightEDTXT?.text.toString())
        }

        startActivity(intent)
    }
```

Também tira as coisas depois do `setContentView` do `onCreate` da ResultCalcIMC que deve funcionar kk

**Comment by blueevee** [comment]
**#maravilhosaaaaaaaaaaa**
